export const data = {
  profile: {
    social: {
      github: "https://github.com/YourMasterIsFool",
      linkedin: "https://www.linkedin.com/in/verrandy23/",
    instagram: "https://instagram.com/verzenbag",
    },
    name: "Verrandy Bagus Prasetyo",
    avatar: "/profile.jpeg",
    email: "verrandyb@gmail.com",
    location: "Bali, Indonesia",
    website: "https://verrandyporto.com.odetejayakreatif.com/",
    jobTitle: "Software Engineer",
    description: "Fullstack, Rust, backend systems, and data platforms",
  },
  about: [
    "Software Engineer with 5+ years of experience building fullstack, backend, and data-intensive systems. Currently contributing at Jobseeker Company as a FullStack Engineer and technical owner for Taekwang V4.",
    "Specialized in Rust data pipelines, distributed asynchronous workers, multi-tenant systems, and reliable product delivery across HR, ATS, organization, and payment domains.",
  ],
  highlights: [
    { value: "5+", label: "Years experience" },
    { value: "1M+", label: "Records processed" },
    { value: "80%", label: "Faster workflows" },
  ],
  coreSkills: [
    "Rust",
    "TypeScript",
    "Axum",
    "Tokio",
    "SQLx",
    "NestJS",
    "Spring Boot",
    "React",
    "Next.js",
    "PostgreSQL",
    "Redis Streams",
    "Docker",
    "Kubernetes",
    "CI/CD",
    "Linux",
  ],
  certifications: ["Junior Mobile Programmer", "Technical Support Professional"],
  education: "Associate Degree in Informatics Engineering - Politeknik Negeri Banyuwangi (2017-2020)",
  academicProject: "Academic final project completed during university as a graduation requirement: a cybersecurity monitoring platform using Cowrie and Dionaea honeypots, GCP attack tracking and analysis, Django, MongoDB logging, and a Java mobile application.",
  experiences: [
    {
      from: "May 2025",
      company: "PT Jobseeker Company",
      to: "Present",
      division: "Fullstack Software Engineer",
      position: "Rust, Backend & Data Platform Focus",
      tools: [
        "Rust",
        "Axum",
        "Tokio",
        "SQLx",
        "NestJS",
        "Spring Boot",
        "React",
        "Next.js",
        "PostgreSQL",
        "Redis Streams",
      ],
      description: [
        "Technical owner for Taekwang V4, coordinating delivery across engineering, QA, DevOps, and business stakeholders.",
        "Built Rust import/export workers and multi-tenant pipelines that process 1M+ records with streaming, batching, and bounded concurrency.",
        "Reduced processing time and server resource consumption by up to 80%.",
        "Designed an OLAP data model with dimensions, facts, aggregate tables, snapshot tables, and temporary aggregation strategies to support scalable analytics and reporting; the design is ready for future implementation.",
        "Developed product capabilities across Organization, ATS, HRIS, Shift Management, and Email Worker domains.",
      ],
    },
    {
      from: "Feb 2020",
      company: "Freelance",
      to: "May 2025",
      division: "Freelance Software Engineer",
      position: "Product & Backend Development",
      tools: ["Nuxt.js", "Next.js", "NestJS", "PostgreSQL", "Xendit", "Duitku"],
      description: [
        "Built Pixel Game from Figma to production with Nuxt.js, Firebase Auth, responsive UI, and clean architecture.",
        "Designed PostgreSQL schemas and developed modular REST APIs with NestJS for flexible roles, transactions, and real-time status tracking.",
        "Integrated Xendit and Duitku payment gateways with secure callback, webhook handling, and transaction validation.",
        "Implemented WhatsApp Business notifications for payment, login, and withdrawal events.",
      ],
    },
    {
      from: "Aug 2023",
      company: "PT Majapahit Teknologi",
      to: "Nov 2024",
      division: "Fullstack Engineer",
      position: "Enterprise Applications",
      tools: ["Laravel", "React", "Angular.js", "SQL", "REST APIs"],
      description: [
        "Created and maintained Business Trip and Reimburse modules for the Mitsubishi project using Laravel Inertia and React.",
        "Maintained and improved the Honda Dealer app with Angular.js and the Bomba audit system with Laravel.",
        "Created REST APIs for SHESINFO and maintained the Stock Opname module in Bisma Service.",
      ],
    },
    {
      from: "Nov 2021",
      company: "PT Ericsson Indonesia",
      to: "Jun 2023",
      division: "Full Stack Engineer",
      position: "Frontend Developer - Contract",
      tools: ["React.js", "Express.js", "REST APIs", "Microsoft SSO"],
      description: [
        "Led frontend development for the DMP Digital Product for ASEAN using React.js and reusable components.",
        "Contributed as a fullstack engineer on the Anza project for Australia and New Zealand using Express.js and React.js.",
        "Implemented Microsoft SSO in the frontend, integrating the authentication flow with backend APIs to retrieve authenticated user data and session context.",
        "Owned end-to-end feature delivery, backend API integration, and production-ready functionality across cross-functional teams.",
      ],
    },
    {
      from: "Feb 2020",
      company: "PT Industri Kereta Api (Persero)",
      to: "Jul 2020",
      division: "Web Developer",
      position: "Project Division",
      tools: ["Laravel", "CodeIgniter 3", "MySQL"],
      description: [
        "Developed the INKA Early Warning web application using Laravel and the Logbook Web application using CodeIgniter 3.",
      ],
    },
    {
      from: "Jun 2019",
      company: "PT Mitratani Dua Tujuh",
      to: "Aug 2019",
      division: "IT Support",
      position: "Internship",
      tools: ["Django", "Python", "Linux", "Networking", "Troubleshooting"],
      description: [
        "Developed an internal problem ticketing system during the internship using Django and Python to help track, manage, and resolve IT issues.",
        "Supported the IT division with internal network troubleshooting and day-to-day technical support.",
      ],
    },
  ],
  projects: [
    {
      link: "https://github.com/YourMasterIsFool/mordern-kitchen-rest-api-golang",
      title: "Modern Kitchen Restaurant Ordering API",
      category: "Learning Project",
      status: "Learning project",
      description: "End-to-end restaurant ordering application built while learning Go and GraphQL, covering menu and ordering workflows through an API-driven backend.",
      tools: ["Golang", "GraphQL", "REST API", "Backend Development"],
    },
    {
      link: "https://github.com/YourMasterIsFool/post-app-axum",
      title: "Shop App - Axum Backend",
      category: "Public Project",
      status: "In progress",
      description: "Backend project for a shop application using Rust and Axum, focused on API-driven product and application workflows.",
      tools: ["Rust", "Axum", "REST API", "Backend Development"],
    },
    {
      link: "https://github.com/YourMasterIsFool/flutter_task_app",
      title: "Flutter Task Management",
      category: "Public Project",
      status: "In progress",
      description: "Flutter mobile application for organizing, tracking, and managing personal tasks.",
      tools: ["Flutter", "Dart", "Mobile Development"],
    },
    {
      link: "https://github.com/YourMasterIsFool/flutter-geopark-smp3",
      title: "Flutter Geopark SMP 3",
      category: "Public Project",
      status: "In progress",
      description: "Flutter mobile application project for exploring and presenting Geopark information and educational content.",
      tools: ["Flutter", "Dart", "Mobile Development"],
    },
    {
      link: "https://github.com/YourMasterIsFool/perpus-frontend",
      title: "Library Management App",
      category: "Public Project",
      description: "Frontend application for a library management experience, covering book browsing and library workflow interfaces.",
      tools: ["Frontend Development", "Library Management", "REST API"],
    },
    {
      link: "https://github.com/YourMasterIsFool/django-pagar-nusa",
      title: "Pagar Nusa Membership System",
      category: "Public Project",
      description: "Membership management system for Pagar Nusa, covering member records and organization administration workflows.",
      tools: ["Django", "Python", "Membership Management"],
    },
    {
      link: "https://github.com/YourMasterIsFool/pemesanan-kos",
      title: "Pemesanan Kos",
      category: "Public Project",
      description: "Web application for searching and managing boarding-house rentals and booking workflows.",
      tools: ["Web Development", "Booking System", "REST API"],
    },
    {
      link: "https://github.com/YourMasterIsFool/laravel-popok-api",
      title: "Reusable Popok - Backend API",
      category: "Public Project",
      description: "Backend API for a reusable diaper product platform, built with Laravel to support product and application workflows.",
      tools: ["Laravel", "PHP", "REST API"],
    },
    {
      link: "https://github.com/YourMasterIsFool/flutter-popok",
      title: "Reusable Popok - Flutter App",
      category: "Public Project",
      description: "Flutter mobile application frontend for the reusable diaper platform, connected to the Laravel backend API.",
      tools: ["Flutter", "Dart", "REST API"],
    },
    {
      link: "https://github.com/YourMasterIsFool/django-shop-vue-plants",
      title: "Django Vue Shop",
      category: "Learning Project",
      status: "Learning project",
      description: "Online shop learning project built with Django and Vue.js, exploring product catalog, browsing, and ordering workflows.",
      tools: ["Django", "Python", "Vue.js", "E-commerce"],
    },
    {
      link: "https://github.com/YourMasterIsFool/BackendHoneypot",
      title: "Academic Final Project - Cybersecurity Honeypot Platform",
      category: "Academic Final Project",
      description: "Completed during university as a graduation requirement. Built a cybersecurity monitoring platform using Cowrie and Dionaea honeypots to capture attacks, Google Cloud Platform to track and analyze attack activity, Django and MongoDB for the backend and security logs, plus a Java mobile app for monitoring insights.",
      tools: ["Cowrie", "Dionaea", "Google Cloud Platform", "Django", "MongoDB", "Java"],
    },
    {
      link: "https://hcms.jobseeker.software/",
      title: "Jobseeker HCMS",
      category: "Enterprise HR Platform",
      description: "HR and organization workflows delivered as part of the Jobseeker V5 platform.",
      tools: ["NestJS", "React", "PostgreSQL", "Redis"],
    },
    {
      link: "https://gojek.jobseeker.software/",
      title: "Gojek HRMS",
      category: "Enterprise HR Platform",
      description: "Contributed to frontend delivery for an enterprise HR management experience on the Jobseeker V5 platform.",
      tools: ["React", "Next.js", "TypeScript"],
    },
    {
      link: "https://tiktok.jobseeker.software/",
      title: "TikTok Careers Platform",
      category: "Career Platform",
      description: "Initiated the careers platform frontend with responsive, production-ready experiences for the Jobseeker V5 platform.",
      tools: ["Next.js", "React", "TypeScript"],
    },
    {
      link: "https://tkg.jobseeker.software/",
      title: "Taekwang V4",
      category: "Featured Enterprise Platform",
      description: "Technical owner and Project PIC for a multi-tenant platform spanning organization, ATS, HRIS, shift management, and email workflows.",
      tools: ["Rust", "NestJS", "React", "PostgreSQL"],
    },
    {
      link: "https://hrms-tkg.jobseeker.software/",
      title: "Taekwang HRMS",
      category: "Enterprise HR Platform",
      description: "Human resource management experience supporting Taekwang enterprise operations and employee workflows.",
      tools: ["React", "NestJS", "PostgreSQL"],
    },
    {
      link: "https://github.com/YourMasterIsFool",
      title: "Pixel Game",
      category: "Freelance Product",
      description:
        "Game top-up platform built with Nuxt 3. Implemented responsive reusable UI from Figma, backend API integration, WebSocket real-time features, payment workflows, and product flows.",
      tools: ["Nuxt 3", "WebSocket", "REST APIs", "Figma"],
    },
    {
      link: "https://github.com/YourMasterIsFool",
      title: "FixyGym",
      category: "Independent Product",
      description:
        "Gym membership and payment platform supporting installment plans, subscriptions, scheduling, transaction tracking, and membership lifecycle management.",
      tools: ["Backend Architecture", "REST APIs", "Payments"],
    },
    {
      link: "https://github.com/YourMasterIsFool/Nabungku",
      title: "Nabungku",
      category: "Personal Project",
      description:
        "Developing simple project Nabungku for my portofolio, using VueJS 2.0 and Laravel. web based for management financial planing like income, expense and goal",
      tools: ["Laravel", "Vue JS 2.0", "Tailwindcss"],
    },

    {
      link: "https://github.com/YourMasterIsFool/flutter_chat",
      title: "Simple Flutter Chat App",
      category: "Personal Project",
      description: "Developing Simple chat app using flutter and firebase",
      tools: ["Flutter", "Firebase"],
    },

    {
      link: "https://github.com/YourMasterIsFool/simple_notes_flutter",
      title: "Simple Notes App",
      category: "Personal Project",
      description: "Developing Simple Notes app using flutter and sqlite",
      tools: ["Flutter", "Sqlite"],
    },
  ],
};
