export const data = {
  profile: {
    social: {
      github: "https://github.com/YourMasterIsFool",
      linkedin: "https://www.linkedin.com/in/verrandy23/",
    instagram: "https://instagram.com/verzenbag",
    },
    name: "Verrandy Bagus Prasetyo",
    avatar: "/profile.jpeg",
    email: "verrandyb@gmail.com",
    location: "Bali, Indonesia",
    website: "https://verrandyporto.com.odetejayakreatif.com/",
    jobTitle: "Software Engineer",
    description: "Fullstack, Rust, backend systems, and data platforms",
  },
  about: [
    "Software Engineer with 5+ years of experience building fullstack, backend, and data-intensive systems. Currently contributing at Jobseeker Company as a FullStack Engineer and technical owner for Taekwang V4.",
    "Specialized in Rust data pipelines, distributed asynchronous workers, multi-tenant systems, and reliable product delivery across HR, ATS, organization, and payment domains.",
  ],
  highlights: [
    { value: "5+", label: "Years experience" },
    { value: "1M+", label: "Records processed" },
    { value: "80%", label: "Faster workflows" },
  ],
  coreSkills: [
    "Rust",
    "TypeScript",
    "Axum",
    "Tokio",
    "SQLx",
    "NestJS",
    "Spring Boot",
    "React",
    "Next.js",
    "PostgreSQL",
    "Redis Streams",
    "Docker",
    "Kubernetes",
    "CI/CD",
    "Linux",
  ],
  certifications: ["Junior Mobile Programmer", "Technical Support Professional"],
  education: "Associate Degree in Informatics Engineering - Politeknik Negeri Banyuwangi (2017-2020)",
  experiences: [
    {
      from: "May 2025",
      company: "PT Jobseeker Company",
      to: "Present",
      division: "Fullstack Software Engineer",
      position: "Rust, Backend & Data Platform Focus",
      tools: [
        "Rust",
        "Axum",
        "Tokio",
        "SQLx",
        "NestJS",
        "Spring Boot",
        "React",
        "Next.js",
        "PostgreSQL",
        "Redis Streams",
      ],
      description: [
        "Technical owner for Taekwang V4, coordinating delivery across engineering, QA, DevOps, and business stakeholders.",
        "Built Rust import/export workers and multi-tenant pipelines that process 1M+ records with streaming, batching, and bounded concurrency.",
        "Reduced processing time and server resource consumption by up to 80%.",
        "Developed product capabilities across Organization, ATS, HRIS, Shift Management, and Email Worker domains.",
      ],
    },
    {
      from: "Feb 2020",
      company: "Freelance",
      to: "May 2025",
      division: "Freelance Software Engineer",
      position: "Product & Backend Development",
      tools: ["Nuxt.js", "Next.js", "NestJS", "PostgreSQL", "Xendit", "Duitku"],
      description: [
        "Built Pixel Game from Figma to production with Nuxt.js, Firebase Auth, responsive UI, and clean architecture.",
        "Designed PostgreSQL schemas and developed modular REST APIs with NestJS for flexible roles, transactions, and real-time status tracking.",
        "Integrated Xendit and Duitku payment gateways with secure callback, webhook handling, and transaction validation.",
        "Implemented WhatsApp Business notifications for payment, login, and withdrawal events.",
      ],
    },
    {
      from: "Aug 2023",
      company: "PT Majapahit Teknologi",
      to: "Nov 2024",
      division: "Fullstack Engineer",
      position: "Enterprise Applications",
      tools: ["Laravel", "React", "Angular.js", "SQL", "REST APIs"],
      description: [
        "Created and maintained Business Trip and Reimburse modules for the Mitsubishi project using Laravel Inertia and React.",
        "Maintained and improved the Honda Dealer app with Angular.js and the Bomba audit system with Laravel.",
        "Created REST APIs for SHESINFO and maintained the Stock Opname module in Bisma Service.",
      ],
    },
    {
      from: "Nov 2021",
      company: "PT Ericsson Indonesia",
      to: "Jun 2023",
      division: "Full Stack Engineer",
      position: "Frontend Developer - Contract",
      tools: ["React.js", "Express.js", "REST APIs"],
      description: [
        "Led frontend development for the DMP Digital Product for ASEAN using React.js and reusable components.",
        "Contributed as a fullstack engineer on the Anza project for Australia and New Zealand using Express.js and React.js.",
        "Owned end-to-end feature delivery, backend API integration, and production-ready functionality across cross-functional teams.",
      ],
    },
    {
      from: "Feb 2020",
      company: "PT Industri Kereta Api (Persero)",
      to: "Jul 2020",
      division: "Web Developer",
      position: "Project Division",
      tools: ["Laravel", "CodeIgniter 3", "MySQL"],
      description: [
        "Developed the INKA Early Warning web application using Laravel and the Logbook Web application using CodeIgniter 3.",
      ],
    },
    {
      from: "Jun 2019",
      company: "PT Mitratani Dua Tujuh",
      to: "Aug 2019",
      division: "IT Support",
      position: "Internship",
      tools: ["Linux", "Networking", "Troubleshooting"],
      description: [
        "Supported the IT division with internal network troubleshooting and day-to-day technical support.",
      ],
    },
  ],
  projects: [
    {
      link: "https://hcms.jobseeker.software/",
      title: "Jobseeker HCMS",
      category: "Enterprise HR Platform",
      description: "HR and organization workflows delivered as part of the Jobseeker V5 platform.",
      tools: ["NestJS", "React", "PostgreSQL", "Redis"],
    },
    {
      link: "https://gojek.jobseeker.software/",
      title: "Gojek HRMS",
      category: "Enterprise HR Platform",
      description: "Contributed to frontend delivery for an enterprise HR management experience on the Jobseeker V5 platform.",
      tools: ["React", "Next.js", "TypeScript"],
    },
    {
      link: "https://tiktok.jobseeker.software/",
      title: "TikTok Careers Platform",
      category: "Career Platform",
      description: "Initiated the careers platform frontend with responsive, production-ready experiences for the Jobseeker V5 platform.",
      tools: ["Next.js", "React", "TypeScript"],
    },
    {
      link: "https://tkg.jobseeker.software/",
      title: "Taekwang V4",
      category: "Featured Enterprise Platform",
      description: "Technical owner and Project PIC for a multi-tenant platform spanning organization, ATS, HRIS, shift management, and email workflows.",
      tools: ["Rust", "NestJS", "React", "PostgreSQL"],
    },
    {
      link: "https://hrms-tkg.jobseeker.software/",
      title: "Taekwang HRMS",
      category: "Enterprise HR Platform",
      description: "Human resource management experience supporting Taekwang enterprise operations and employee workflows.",
      tools: ["React", "NestJS", "PostgreSQL"],
    },
    {
      link: "https://github.com/YourMasterIsFool",
      title: "Pixel Game",
      category: "Freelance Product",
      description:
        "Game top-up platform built with Nuxt 3. Implemented responsive reusable UI from Figma, backend API integration, WebSocket real-time features, payment workflows, and product flows.",
      tools: ["Nuxt 3", "WebSocket", "REST APIs", "Figma"],
    },
    {
      link: "https://github.com/YourMasterIsFool",
      title: "FixyGym",
      category: "Independent Product",
      description:
        "Gym membership and payment platform supporting installment plans, subscriptions, scheduling, transaction tracking, and membership lifecycle management.",
      tools: ["Backend Architecture", "REST APIs", "Payments"],
    },
    {
      link: "https://github.com/YourMasterIsFool/Nabungku",
      title: "Nabungku",
      category: "Personal Project",
      description:
        "Developing simple project Nabungku for my portofolio, using VueJS 2.0 and Laravel. web based for management financial planing like income, expense and goal",
      tools: ["Laravel", "Vue JS 2.0", "Tailwindcss"],
    },

    {
      link: "https://github.com/YourMasterIsFool/flutter_chat",
      title: "Simple Flutter Chat App",
      category: "Personal Project",
      description: "Developing Simple chat app using flutter and firebase",
      tools: ["Flutter", "Firebase"],
    },

    {
      link: "https://github.com/YourMasterIsFool/simple_notes_flutter",
      title: "Simple Notes App",
      category: "Personal Project",
      description: "Developing Simple Notes app using flutter and sqlite",
      tools: ["Flutter", "Sqlite"],
    },
  ],
};
